Authentication/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_users.urls'))
]

learning_users/urls.py
from django.urls import path
from . import views

app_name='learning_users'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('special/',views.special,name='special')
]

learning_users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    # Create relationtship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE) # This is like an extension of the User class

    #addtional attributes
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learning_users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=('username','password','email')



class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

learning_users/views.py
from django.shortcuts import render
from learning_users.models import UserProfileInfo
from .forms import UserProfileInfoForm,UserForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout


# Create your views here.


def index(request):
    return render(request,'learning_users/index.html')

def register(request):
    registered=False

    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save() #saving form data to db
            user.set_password(user.password) #hashing the save password
            user.save() #saving the hashed password

            profile=profile_form.save(commit=False) #does not commit to db yet
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print((user_form.errors,profile_form.errors))

    else:
        user_form = UserForm(None)
        profile_form = UserProfileInfoForm(None)

    return render(request,'learning_users/registration.html',{'user_form':user_form,
                                                             'profile_form':profile_form,
                                                             'registered':registered
                                                             })

def user_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('learning_users:index'))
            else:
                return HttpResponse('Account not active')

        else:
            print('Someoen tried to login and failed')
            print('Username {} and password {}'.format(username,password))
            return HttpResponse('Invalid login detail supplied!')
    else:
        return render(request,'learning_users/login.html')


@login_required #decorator that make sure this view is called only if user is logged in
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_users:index'))

@login_required
def special(request):
    return HttpResponse('You are logged in !.')

templates/learning_users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    <!-- load static files -->

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark  bg-dark" style="padding: 2px">
  <a class="navbar-brand" href="{% url 'learning_users:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li class="nav-item"><a class="navbar-link" href="{% url 'learning_users:register' %}">&nbsp;&nbsp;Register</a></li>
       {% if user.is_authenticated %}
           <li><a class="navbar-link" href="{% url 'learning_users:user_logout' %}">&nbsp;&nbsp;Logout</a></li>
       {% else %}
           <li><a class="navbar-link" href="{% url 'learning_users:user_login' %}">&nbsp;&nbsp;Login</a></li>
       {% endif %}

    </ul>
  </div>

</nav>
<div class="container">
 {% block body%}{% endblock %}
</div>


</body>
</html>

templates/learning_users/index.html
{% extends 'learning_users/base.html' %}
{% block body %}
    <div class="jumbotron">
    <h2>User Registration System</h2>
    </div>

{% endblock %}

templates/learning_users/login.html
{% extends 'learning_users/base.html' %}
{% block body %}

    <div class="jumbotron">
    <h1>LOGIN!</h1>
    <form method="post" action="{% url 'learning_users:user_login' %}">
        {% csrf_token %}
        <label for="username">UserName:</label>
        <input type="text" name="username" placeholder="Enter UserName" >

        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="submit" value="LOGIN">

    </form>
    </div>

{% endblock %}

templates/learning_users/registration.html
{% extends 'learning_users/base.html' %}
{% load staticfiles %}
{% block body %}
    <div class="jumbotron">
    {% if registered %}
        <h2>Thank you for registering!</h2>

    {% else %}
    <h1 style="font-style: italic">Register Here</h1>
    <h2 style="font-style: italic">Fill out the form:</h2>
    <br>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register">
    </form>


    {% endif %}


    </div>

{% endblock %}